language: cpp

dist: focal 
addons:
    apt:
        packages:
            - libxkbcommon-x11-0
            - libgl1-mesa-dev
services: 
    - xvfb
cache:
    - pip
before_install:
    - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
    - git fetch origin master
    - sudo bash -c 'echo "deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates universe" >> /etc/apt/sources.list'
    - sudo bash -c 'echo "deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-updates universe" >> /etc/apt/sources.list'
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq cmake
    - cmake --version
script:
    - cd build/release 
    - cmake -DCMAKE_BUILD_TYPE=Release ../..
    - make -j4
    - cd ../debug
    - cmake -DCMAKE_BUILD_TYPE=Debug ../..
    - make -j4